appName: booking-service
createService: true
deploymentName: booking-service-v1

replicaCount: 1

image:
  name: booking-service
  tag: latest
  pullPolicy: Never

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

env:
  - name: ENABLE_FEATURE_X
    value: "false"
  - name: VERSION
    value: "v1"

version: v1

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

livenessProbe:
  path: /ping
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  path: /ready
  initialDelaySeconds: 3
  periodSeconds: 5
